using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LanguageRegionData
{
    public class CountryData
    {
        public string Country = "";
        public string Language = "";
        public string LanguageCode = "";
        public string CountryCode = "";
        public string NumCode = "";
        public string Currency = "";
        
    }


    public static List<CountryData> Country = new() {

    new(){Country="Saudi Arabia", Language="Arabic", LanguageCode="ar", CountryCode="SA", NumCode="966", Currency="Riyal"},
    new(){Country="Bulgaria", Language="Bulgarian", LanguageCode="bg", CountryCode="BG", NumCode="359", Currency="Lev"},
    new(){Country="Spain", Language="Catalan", LanguageCode="ca", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="China", Language="Chinese (Simplified)", LanguageCode="zh-Hans", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="Czech Republic", Language="Czech", LanguageCode="cs", CountryCode="CZ", NumCode="420", Currency="Koruna"},
    new(){Country="Denmark", Language="Danish", LanguageCode="da", CountryCode="DK", NumCode="45", Currency="Krone"},
    new(){Country="Germany", Language="German", LanguageCode="de", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="Greece", Language="Greek", LanguageCode="el", CountryCode="GR", NumCode="30", Currency="Euro"},
    new(){Country="United Kingdom", Language="English", LanguageCode="en", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Spain", Language="Spanish", LanguageCode="es", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="Finland", Language="Finnish", LanguageCode="fi", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="France", Language="French", LanguageCode="fr", CountryCode="FR", NumCode="33", Currency="Euro"},
    new(){Country="Israel", Language="Hebrew", LanguageCode="he", CountryCode="IL", NumCode="972", Currency="Shekel"},
    new(){Country="Hungary", Language="Hungarian", LanguageCode="hu", CountryCode="HU", NumCode="36", Currency="Forint"},
    new(){Country="Iceland", Language="Icelandic", LanguageCode="is", CountryCode="IS", NumCode="354", Currency="Krona"},
    new(){Country="Italy", Language="Italian", LanguageCode="it", CountryCode="IT", NumCode="39", Currency="Euro"},
    new(){Country="Japan", Language="Japanese", LanguageCode="ja", CountryCode="JP", NumCode="81", Currency="Yen"},
    new(){Country="South Korea", Language="Korean", LanguageCode="ko", CountryCode="KR", NumCode="82", Currency="Won"},
    new(){Country="Netherlands", Language="Dutch", LanguageCode="nl", CountryCode="NL", NumCode="31", Currency="Euro"},
    new(){Country="Norway", Language="Norwegian", LanguageCode="no", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Poland", Language="Polish", LanguageCode="pl", CountryCode="PL", NumCode="48", Currency="Zloty"},
    new(){Country="Portugal", Language="Portuguese", LanguageCode="pt", CountryCode="PT", NumCode="351", Currency="Euro"},
    new(){Country="Switzerland", Language="Romansh", LanguageCode="rm", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="Romania", Language="Romanian", LanguageCode="ro", CountryCode="RO", NumCode="40", Currency="Leu"},
    new(){Country="Russia", Language="Russian", LanguageCode="ru", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="Croatia", Language="Croatian", LanguageCode="hr", CountryCode="HR", NumCode="385", Currency="Kuna"},
    new(){Country="Slovakia", Language="Slovak", LanguageCode="sk", CountryCode="SK", NumCode="421", Currency="Euro"},
    new(){Country="Albania", Language="Albanian", LanguageCode="sq", CountryCode="AL", NumCode="355", Currency="Lek"},
    new(){Country="Sweden", Language="Swedish", LanguageCode="sv", CountryCode="SE", NumCode="46", Currency="Krona"},
    new(){Country="Thailand", Language="Thai", LanguageCode="th", CountryCode="TH", NumCode="66", Currency="Baht"},
    new(){Country="Turkey", Language="Turkish", LanguageCode="tr", CountryCode="TR", NumCode="90", Currency="Lira"},
    new(){Country="Pakistan", Language="Urdu", LanguageCode="ur", CountryCode="PK", NumCode="92", Currency="Rupee"},
    new(){Country="Indonesia", Language="Indonesian", LanguageCode="id", CountryCode="ID", NumCode="62", Currency="Rupiah"},
    new(){Country="Ukraine", Language="Ukrainian", LanguageCode="uk", CountryCode="UA", NumCode="380", Currency="Hryvnia"},
    new(){Country="Belarus", Language="Belarusian", LanguageCode="be", CountryCode="BY", NumCode="375", Currency="Ruble"},
    new(){Country="Slovenia", Language="Slovenian", LanguageCode="sl", CountryCode="SI", NumCode="386", Currency="Euro"},
    new(){Country="Estonia", Language="Estonian", LanguageCode="et", CountryCode="EE", NumCode="372", Currency="Euro"},
    new(){Country="Latvia", Language="Latvian", LanguageCode="lv", CountryCode="LV", NumCode="371", Currency="Euro"},
    new(){Country="Lithuania", Language="Lithuanian", LanguageCode="lt", CountryCode="LT", NumCode="370", Currency="Euro"},
    new(){Country="Tajikistan", Language="Tajik", LanguageCode="tg", CountryCode="TJ", NumCode="992", Currency="Somoni"},
    new(){Country="Iran", Language="Persian", LanguageCode="fa", CountryCode="IR", NumCode="98", Currency="Rial"},
    new(){Country="Vietnam", Language="Vietnamese", LanguageCode="vi", CountryCode="VN", NumCode="84", Currency="Dong"},
    new(){Country="Armenia", Language="Armenian", LanguageCode="hy", CountryCode="AM", NumCode="374", Currency="Dram"},
    new(){Country="Azerbaijan", Language="Azerbaijani", LanguageCode="az", CountryCode="AZ", NumCode="994", Currency="Manat"},
    new(){Country="Spain", Language="Basque", LanguageCode="eu", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="Germany", Language="Upper Sorbian", LanguageCode="hsb", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="North Macedonia", Language="Macedonian", LanguageCode="mk", CountryCode="MK", NumCode="389", Currency="Denar"},
    new(){Country="South Africa", Language="Southern Sotho", LanguageCode="st", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Tsonga", LanguageCode="ts", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Tswana", LanguageCode="tn", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Xhosa", LanguageCode="xh", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Zulu", LanguageCode="zu", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Afrikaans", LanguageCode="af", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="Georgia", Language="Georgian", LanguageCode="ka", CountryCode="GE", NumCode="995", Currency="Lari"},
    new(){Country="Faroe Islands", Language="Faroese", LanguageCode="fo", CountryCode="FO", NumCode="298", Currency="Króna"},
    new(){Country="India", Language="Hindi", LanguageCode="hi", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Malta", Language="Maltese", LanguageCode="mt", CountryCode="MT", NumCode="356", Currency="Euro"},
    new(){Country="Norway", Language="Northern Sami", LanguageCode="se", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Ireland", Language="Irish", LanguageCode="ga", CountryCode="IE", NumCode="353", Currency="Euro"},
    new(){Country="Malaysia", Language="Malay", LanguageCode="ms", CountryCode="MY", NumCode="60", Currency="Ringgit"},
    new(){Country="Kazakhstan", Language="Kazakh", LanguageCode="kk", CountryCode="KZ", NumCode="7", Currency="Tenge"},
    new(){Country="Kyrgyzstan", Language="Kyrgyz", LanguageCode="ky", CountryCode="KG", NumCode="996", Currency="Som"},
    new(){Country="Tanzania", Language="Swahili", LanguageCode="SW", CountryCode="TZ", NumCode="255", Currency="Shilling"},
    new(){Country="Turkmenistan", Language="Turkmen", LanguageCode="tk", CountryCode="TM", NumCode="993", Currency="Manat"},
    new(){Country="Uzbekistan", Language="Uzbek", LanguageCode="uz", CountryCode="UZ", NumCode="998", Currency="Som"},
    new(){Country="Russia", Language="Tatar", LanguageCode="tt", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="Bangladesh", Language="Bangla", LanguageCode="bn", CountryCode="BD", NumCode="880", Currency="Taka"},
    new(){Country="Pakistan", Language="Punjabi", LanguageCode="pa", CountryCode="PK", NumCode="92", Currency="Rupee"},
    new(){Country="India", Language="Gujarati", LanguageCode="gu", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Odia", LanguageCode="or", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Tamil", LanguageCode="ta", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Telugu", LanguageCode="te", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Kannada", LanguageCode="kn", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Malayalam", LanguageCode="ml", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Assamese", LanguageCode="as", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Marathi", LanguageCode="mr", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Mongolia", Language="Mongolian", LanguageCode="mn", CountryCode="MN", NumCode="976", Currency="Tögrög"},
    new(){Country="China", Language="Tibetan", LanguageCode="bo", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="Wales", Language="Welsh", LanguageCode="cy", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Cambodia", Language="Khmer", LanguageCode="km", CountryCode="KH", NumCode="855", Currency="Riel"},
    new(){Country="Laos", Language="Lao", LanguageCode="lo", CountryCode="LA", NumCode="856", Currency="Kip"},
    new(){Country="Myanmar", Language="Burmese", LanguageCode="my", CountryCode="MM", NumCode="95", Currency="Kyat"},
    new(){Country="Spain", Language="Galician", LanguageCode="gli", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="India", Language="Konkani", LanguageCode="kok", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Sri Lanka", Language="Sinhala", LanguageCode="si", CountryCode="LK", NumCode="94", Currency="Rupee"},
    new(){Country="United States", Language="Cherokee", LanguageCode="chr", CountryCode="US", NumCode="1", Currency="Dollar"},
    new(){Country="Ethiopia", Language="Amharic", LanguageCode="am", CountryCode="ET", NumCode="251", Currency="Birr"},
    new(){Country="Morocco", Language="Central Atlas Tamazight", LanguageCode="tzm", CountryCode="MA", NumCode="212", Currency="Dirham"},
    new(){Country="Nepal", Language="Nepali", LanguageCode="ne", CountryCode="NP", NumCode="977", Currency="Rupee"},
    new(){Country="Netherlands", Language="Western Frisian", LanguageCode="fy", CountryCode="NL", NumCode="31", Currency="Euro"},
    new(){Country="Afghanistan", Language="Pashto", LanguageCode="ps", CountryCode="AF", NumCode="93", Currency="Afghani"},
    new(){Country="Philippines", Language="Filipino", LanguageCode="fil", CountryCode="PH", NumCode="63", Currency="Peso"},
    new(){Country="Nigeria", Language="Fulah", LanguageCode="ff", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="Nigeria", Language="Hausa", LanguageCode="ha", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="Nigeria", Language="Yoruba", LanguageCode="yo", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="South Africa", Language="Northern Sotho", LanguageCode="nso", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="Luxembourg", Language="Luxembourgish", LanguageCode="lb", CountryCode="LU", NumCode="352", Currency="Euro"},
    new(){Country="Greenland", Language="Kalaallisut", LanguageCode="kl", CountryCode="GL", NumCode="299", Currency="Krone"},
    new(){Country="Nigeria", Language="Igbo", LanguageCode="ig", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="Ethiopia", Language="Oromo", LanguageCode="om", CountryCode="ET", NumCode="251", Currency="Birr"},
    new(){Country="Eritrea", Language="Tigrinya", LanguageCode="ti", CountryCode="ER", NumCode="291", Currency="Nakfa"},
    new(){Country="United States", Language="Hawaiian", LanguageCode="haw", CountryCode="US", NumCode="1", Currency="Dollar"},
    new(){Country="Somalia", Language="Somali", LanguageCode="so", CountryCode="SO", NumCode="252", Currency="Shilling"},
    new(){Country="China", Language="Sichuan Yi", LanguageCode="ii", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="France", Language="Breton", LanguageCode="br", CountryCode="FR", NumCode="33", Currency="Euro"},
    new(){Country="China", Language="Uyghur", LanguageCode="ug", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="Switzerland", Language="Swiss German", LanguageCode="gsw", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="Russia", Language="Sakha", LanguageCode="sah", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="Rwanda", Language="Kinyarwanda", LanguageCode="rw", CountryCode="RW", NumCode="250", Currency="Franc"},
    new(){Country="United Kingdom", Language="Scottish Gaelic", LanguageCode="gd", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Saudi Arabia", Language="Arabic", LanguageCode="ar-SA", CountryCode="SA", NumCode="966", Currency="Riyal"},
    new(){Country="Bulgaria", Language="Bulgarian", LanguageCode="bg-BG", CountryCode="BG", NumCode="359", Currency="Lev"},
    new(){Country="Spain", Language="Catalan", LanguageCode="ca-ES", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="Taiwan", Language="Chinese (Traditional)", LanguageCode="zh-TW", CountryCode="TW", NumCode="886", Currency="New Taiwan Dollar"},
    new(){Country="Czech Republic", Language="Czech", LanguageCode="cs-CZ", CountryCode="CZ", NumCode="420", Currency="Koruna"},
    new(){Country="Denmark", Language="Danish", LanguageCode="da-DK", CountryCode="DK", NumCode="45", Currency="Krone"},
    new(){Country="Germany", Language="German", LanguageCode="de-DE", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="Greece", Language="Greek", LanguageCode="el-GR", CountryCode="GR", NumCode="30", Currency="Euro"},
    new(){Country="United States", Language="English", LanguageCode="en-US", CountryCode="US", NumCode="1", Currency="Dollar"},
    new(){Country="Finland", Language="Finnish", LanguageCode="fi-FI", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="France", Language="French", LanguageCode="fr-FR", CountryCode="FR", NumCode="33", Currency="Euro"},
    new(){Country="Israel", Language="Hebrew", LanguageCode="he-IL", CountryCode="IL", NumCode="972", Currency="Shekel"},
    new(){Country="Hungary", Language="Hungarian", LanguageCode="hu-HU", CountryCode="HU", NumCode="36", Currency="Forint"},
    new(){Country="Iceland", Language="Icelandic", LanguageCode="is-IS", CountryCode="IS", NumCode="354", Currency="Krona"},
    new(){Country="Italy", Language="Italian", LanguageCode="it-IT", CountryCode="IT", NumCode="39", Currency="Euro"},
    new(){Country="Japan", Language="Japanese", LanguageCode="ja-JP", CountryCode="JP", NumCode="81", Currency="Yen"},
    new(){Country="South Korea", Language="Korean", LanguageCode="ko-KR", CountryCode="KR", NumCode="82", Currency="Won"},
    new(){Country="Netherlands", Language="Dutch", LanguageCode="nl-NL", CountryCode="NL", NumCode="31", Currency="Euro"},
    new(){Country="Norway", Language="Norwegian Bokmal", LanguageCode="nb-NO", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Poland", Language="Polish", LanguageCode="pl-PL", CountryCode="PL", NumCode="48", Currency="Zloty"},
    new(){Country="Brazil", Language="Portuguese", LanguageCode="pt-BR", CountryCode="BR", NumCode="55", Currency="Real"},
    new(){Country="Switzerland", Language="Romansh", LanguageCode="rm-CH", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="Romania", Language="Romanian", LanguageCode="ro-RO", CountryCode="RO", NumCode="40", Currency="Leu"},
    new(){Country="Russia", Language="Russian", LanguageCode="ru-RU", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="Croatia", Language="Croatian", LanguageCode="hr-HR", CountryCode="HR", NumCode="385", Currency="Kuna"},
    new(){Country="Slovakia", Language="Slovak", LanguageCode="sk-SK", CountryCode="SK", NumCode="421", Currency="Euro"},
    new(){Country="Albania", Language="Albanian", LanguageCode="sq-AL", CountryCode="AL", NumCode="355", Currency="Lek"},
    new(){Country="Sweden", Language="Swedish", LanguageCode="sv-SE", CountryCode="SE", NumCode="46", Currency="Krona"},
    new(){Country="Thailand", Language="Thai", LanguageCode="th-TH", CountryCode="TH", NumCode="66", Currency="Baht"},
    new(){Country="Turkey", Language="Turkish", LanguageCode="tr-TR", CountryCode="TR", NumCode="90", Currency="Lira"},
    new(){Country="Pakistan", Language="Urdu", LanguageCode="ur-PK", CountryCode="PK", NumCode="92", Currency="Rupee"},
    new(){Country="Indonesia", Language="Indonesian", LanguageCode="id-ID", CountryCode="ID", NumCode="62", Currency="Rupiah"},
    new(){Country="Ukraine", Language="Ukrainian", LanguageCode="uk-UA", CountryCode="UA", NumCode="380", Currency="Hryvnia"},
    new(){Country="Belarus", Language="Belarusian", LanguageCode="be-BY", CountryCode="BY", NumCode="375", Currency="Ruble"},
    new(){Country="Slovenia", Language="Slovenian", LanguageCode="sl-SI", CountryCode="SI", NumCode="386", Currency="Euro"},
    new(){Country="Estonia", Language="Estonian", LanguageCode="et-EE", CountryCode="EE", NumCode="372", Currency="Euro"},
    new(){Country="Latvia", Language="Latvian", LanguageCode="lv-LV", CountryCode="LV", NumCode="371", Currency="Euro"},
    new(){Country="Lithuania", Language="Lithuanian", LanguageCode="lt-LT", CountryCode="LT", NumCode="370", Currency="Euro"},
    new(){Country="Tajikistan", Language="Tajik (Cyrillic)", LanguageCode="tg-Cyrl-TJ", CountryCode="TJ", NumCode="992", Currency="Somoni"},
    new(){Country="Iran", Language="Persian", LanguageCode="fa-IR", CountryCode="IR", NumCode="98", Currency="Rial"},
    new(){Country="Vietnam", Language="Vietnamese", LanguageCode="vi-VN", CountryCode="VN", NumCode="84", Currency="Dong"},
    new(){Country="Armenia", Language="Armenian", LanguageCode="hy-AM", CountryCode="AM", NumCode="374", Currency="Dram"},
    new(){Country="Azerbaijan", Language="Azerbaijani (Latin)", LanguageCode="az-Latn-AZ", CountryCode="AZ", NumCode="994", Currency="Manat"},
    new(){Country="Spain", Language="Basque", LanguageCode="eu-ES", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="Germany", Language="Upper Sorbian", LanguageCode="hsb-DE", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="North Macedonia", Language="Macedonian", LanguageCode="mk-MK", CountryCode="MK", NumCode="389", Currency="Denar"},
    new(){Country="South Africa", Language="Southern Sotho", LanguageCode="st-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Tsonga", LanguageCode="ts-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Tswana", LanguageCode="tn-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Xhosa", LanguageCode="xh-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Zulu", LanguageCode="zu-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="South Africa", Language="Afrikaans", LanguageCode="af-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="Georgia", Language="Georgian", LanguageCode="ka-GE", CountryCode="GE", NumCode="995", Currency="Lari"},
    new(){Country="Faroe Islands", Language="Faroese", LanguageCode="fo-FO", CountryCode="FO", NumCode="298", Currency="Króna"},
    new(){Country="India", Language="Hindi", LanguageCode="hi-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Malta", Language="Maltese", LanguageCode="", CountryCode="MT", NumCode="356", Currency="Euro"},
    new(){Country="Norway", Language="Northern Sami", LanguageCode="se-NO", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Malaysia", Language="Malay", LanguageCode="ms-MY", CountryCode="MY", NumCode="60", Currency="Ringgit"},
    new(){Country="Kazakhstan", Language="Kazakh", LanguageCode="kk-KZ", CountryCode="KZ", NumCode="7", Currency="Tenge"},
    new(){Country="Kyrgyzstan", Language="Kyrgyz", LanguageCode="ky-KG", CountryCode="KG", NumCode="996", Currency="Som"},
    new(){Country="Kenya", Language="Swahili", LanguageCode="sw-KE", CountryCode="KE", NumCode="254", Currency="Shilling"},
    new(){Country="Turkmenistan", Language="Turkmen", LanguageCode="tk-TM", CountryCode="TM", NumCode="993", Currency="Manat"},
    new(){Country="Uzbekistan", Language="Uzbek (Latin)", LanguageCode="uz-Latn-UZ", CountryCode="UZ", NumCode="998", Currency="Som"},
    new(){Country="Russia", Language="Tatar", LanguageCode="tt-RU", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="India", Language="Bangla", LanguageCode="bn-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Gujarati", LanguageCode="gu-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Odia", LanguageCode="or-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Tamil", LanguageCode="ta-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Telugu", LanguageCode="te-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Kannada", LanguageCode="kn-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Malayalam", LanguageCode="ml-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Assamese", LanguageCode="as-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="India", Language="Marathi", LanguageCode="mr-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Mongolia", Language="Mongolian", LanguageCode="mn-MN", CountryCode="MN", NumCode="976", Currency="Tögrög"},
    new(){Country="China", Language="Tibetan", LanguageCode="bo-CN", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="United Kingdom", Language="Welsh", LanguageCode="cy-GB", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Cambodia", Language="Khmer", LanguageCode="km-KH", CountryCode="KH", NumCode="855", Currency="Riel"},
    new(){Country="Laos", Language="Lao", LanguageCode="lo-LA", CountryCode="LA", NumCode="856", Currency="Kip"},
    new(){Country="Myanmar (Burma)", Language="Burmese", LanguageCode="my-MM", CountryCode="MM", NumCode="95", Currency="Kyat"},
    new(){Country="Spain", Language="Galician", LanguageCode="gl-ES", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="India", Language="Konkani", LanguageCode="kok-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Sri Lanka", Language="Sinhala", LanguageCode="si-LK", CountryCode="LK", NumCode="94", Currency="Rupee"},
    new(){Country="Ethiopia", Language="Amharic", LanguageCode="am-ET", CountryCode="ET", NumCode="251", Currency="Birr"},
    new(){Country="Nepal", Language="Nepali", LanguageCode="ne-NP", CountryCode="NP", NumCode="977", Currency="Rupee"},
    new(){Country="Netherlands", Language="Western Frisian", LanguageCode="fy-NL", CountryCode="NL", NumCode="31", Currency="Euro"},
    new(){Country="Afghanistan", Language="Pashto", LanguageCode="ps-AF", CountryCode="AF", NumCode="93", Currency="Afghani"},
    new(){Country="Philippines", Language="Filipino", LanguageCode="fil-PH", CountryCode="PH", NumCode="63", Currency="Peso"},
    new(){Country="Nigeria", Language="Hausa (Latin)", LanguageCode="ha-Latn-NG", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="Nigeria", Language="Yoruba", LanguageCode="yo-NG", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="South Africa", Language="Northern Sotho", LanguageCode="nso-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="Luxembourg", Language="Luxembourgish", LanguageCode="lb-LU", CountryCode="LU", NumCode="352", Currency="Euro"},
    new(){Country="Greenland", Language="Kalaallisut", LanguageCode="kl-GL", CountryCode="GL", NumCode="299", Currency="Krone"},
    new(){Country="Nigeria", Language="Igbo", LanguageCode="ig-NG", CountryCode="NG", NumCode="234", Currency="Naira"},
    new(){Country="Ethiopia", Language="Oromo", LanguageCode="om-ET", CountryCode="ET", NumCode="251", Currency="Birr"},
    new(){Country="Ethiopia", Language="Tigrinya", LanguageCode="ti-ET", CountryCode="ET", NumCode="251", Currency="Nakfa"},
    new(){Country="United States", Language="Hawaiian", LanguageCode="haw-US", CountryCode="US", NumCode="1", Currency="Dollar"},
    new(){Country="Somalia", Language="Somali", LanguageCode="so-SO", CountryCode="SO", NumCode="252", Currency="Shilling"},
    new(){Country="China", Language="Sichuan Yi", LanguageCode="ii-CN", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="France", Language="Breton", LanguageCode="br-FR", CountryCode="FR", NumCode="33", Currency="Euro"},
    new(){Country="China", Language="Uyghur", LanguageCode="ug-CN", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="France", Language="Swiss German", LanguageCode="gsw-FR", CountryCode="FR", NumCode="33", Currency="Euro"},
    new(){Country="Russia", Language="Sakha", LanguageCode="sah-RU", CountryCode="RU", NumCode="7", Currency="Ruble"},
    new(){Country="Rwanda", Language="Kinyarwanda", LanguageCode="rw-RW", CountryCode="RW", NumCode="250", Currency="Franc"},
    new(){Country="United Kingdom", Language="Scottish Gaelic", LanguageCode="gd-GB", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Iraq", Language="Arabic", LanguageCode="ar-IQ", CountryCode="IQ", NumCode="964", Currency="Dinar"},
    new(){Country="Spain", Language="Catalan", LanguageCode="ca-ES-valencia", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="China", Language="Chinese (Simplified)", LanguageCode="zh-CN", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="Switzerland", Language="German", LanguageCode="de-CH", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="United Kingdom", Language="English", LanguageCode="en-GB", CountryCode="GB", NumCode="44", Currency="Pound"},
    new(){Country="Mexico", Language="Spanish", LanguageCode="es-MX", CountryCode="MX", NumCode="52", Currency="Peso"},
    new(){Country="Belgium", Language="French", LanguageCode="fr-BE", CountryCode="BE", NumCode="32", Currency="Euro"},
    new(){Country="Switzerland", Language="Italian", LanguageCode="it-CH", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="Belgium", Language="Dutch", LanguageCode="nl-BE", CountryCode="BE", NumCode="32", Currency="Euro"},
    new(){Country="Norway", Language="Norwegian Nynorsk", LanguageCode="nn-NO", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Portugal", Language="Portuguese", LanguageCode="pt-PT", CountryCode="PT", NumCode="351", Currency="Euro"},
    new(){Country="Moldova", Language="Romanian", LanguageCode="ro-MD", CountryCode="MD", NumCode="373", Currency="Leu"},
    new(){Country="Moldova", Language="Russian", LanguageCode="ru-MD", CountryCode="MD", NumCode="373", Currency="Leu"},
    new(){Country="Finland", Language="Swedish", LanguageCode="SV-FI", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="India", Language="Urdu", LanguageCode="ur-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Azerbaijan", Language="Azerbaijani (Cyrillic)", LanguageCode="az-Cyrl-AZ", CountryCode="AZ", NumCode="994", Currency="Manat"},
    new(){Country="Germany", Language="Lower Sorbian", LanguageCode="dsb-DE", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="Botswana", Language="Tswana", LanguageCode="tn-BW", CountryCode="BW", NumCode="267", Currency="Pula"},
    new(){Country="Sweden", Language="Northern Sami", LanguageCode="se-SE", CountryCode="SE", NumCode="46", Currency="Krona"},
    new(){Country="Ireland", Language="Irish", LanguageCode="ga-IE", CountryCode="IE", NumCode="353", Currency="Euro"},
    new(){Country="Brunei", Language="Malay", LanguageCode="ms-BN", CountryCode="BN", NumCode="673", Currency="Dollar"},
    new(){Country="Uzbekistan", Language="Uzbek (Cyrillic)", LanguageCode="uz-Cyrl-UZ", CountryCode="UZ", NumCode="998", Currency="Som"},
    new(){Country="Bangladesh", Language="Bangla", LanguageCode="bn-BD", CountryCode="BD", NumCode="880", Currency="Taka"},
    new(){Country="Pakistan", Language="Punjabi (Arabic)", LanguageCode="pa-Arab-PK", CountryCode="PK", NumCode="92", Currency="Rupee"},
    new(){Country="Sri Lanka", Language="Tamil", LanguageCode="ta-LK", CountryCode="LK", NumCode="94", Currency="Rupee"},
    new(){Country="India", Language="Nepali", LanguageCode="ne-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Eritrea", Language="Tigrinya", LanguageCode="ti-ER", CountryCode="ER", NumCode="291", Currency="Nakfa"},
    new(){Country="Egypt", Language="Arabic", LanguageCode="ar-EG", CountryCode="EG", NumCode="20", Currency="Pound"},
    new(){Country="Hong Kong SAR China", Language="Chinese (Traditional)", LanguageCode="zh-HK", CountryCode="HK", NumCode="852", Currency="Dollar"},
    new(){Country="Austria", Language="German", LanguageCode="de-AT", CountryCode="AT", NumCode="43", Currency="Euro"},
    new(){Country="Australia", Language="English", LanguageCode="en-AU", CountryCode="AU", NumCode="61", Currency="Dollar"},
    new(){Country="Spain", Language="Spanish", LanguageCode="es-ES", CountryCode="ES", NumCode="34", Currency="Euro"},
    new(){Country="Canada", Language="French", LanguageCode="fr-CA", CountryCode="CA", NumCode="1", Currency="Dollar"},
    new(){Country="Finland", Language="Northern Sami", LanguageCode="se-FI", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="Libya", Language="Arabic", LanguageCode="ar-LY", CountryCode="LY", NumCode="218", Currency="Dinar"},
    new(){Country="Singapore", Language="Chinese (Simplified)", LanguageCode="zh-SG", CountryCode="SG", NumCode="65", Currency="Dollar"},
    new(){Country="Luxembourg", Language="German", LanguageCode="de-LU", CountryCode="LU", NumCode="352", Currency="Euro"},
    new(){Country="Canada", Language="English", LanguageCode="en-CA", CountryCode="CA", NumCode="1", Currency="Dollar"},
    new(){Country="Guatemala", Language="Spanish", LanguageCode="es-GT", CountryCode="GT", NumCode="502", Currency="Quetzal"},
    new(){Country="Switzerland", Language="French", LanguageCode="fr-CH", CountryCode="CH", NumCode="41", Currency="Franc"},
    new(){Country="Bosnia & Herzegovina", Language="Croatian (Latin)", LanguageCode="hr-BA", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Algeria", Language="Arabic", LanguageCode="ar-DZ", CountryCode="DZ", NumCode="213", Currency="Dinar"},
    new(){Country="Macau SAR China", Language="Chinese (Traditional)", LanguageCode="zh-MO", CountryCode="MO", NumCode="853", Currency="Pataca"},
    new(){Country="Liechtenstein", Language="German", LanguageCode="de-LI", CountryCode="LI", NumCode="423", Currency="Swiss Franc"},
    new(){Country="New Zealand", Language="English", LanguageCode="en-NZ", CountryCode="NZ", NumCode="64", Currency="Dollar"},
    new(){Country="Costa Rica", Language="Spanish", LanguageCode="es-CR", CountryCode="CR", NumCode="506", Currency="Colon"},
    new(){Country="Luxembourg", Language="French", LanguageCode="fr-LU", CountryCode="LU", NumCode="352", Currency="Euro"},
    new(){Country="Bosnia & Herzegovina", Language="Bosnian (Latin)", LanguageCode="bs-Latn-BA", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Tunisia", Language="Arabic", LanguageCode="ar-TN", CountryCode="TN", NumCode="216", Currency="Dinar"},
    new(){Country="South Africa", Language="English", LanguageCode="en-ZA", CountryCode="ZA", NumCode="27", Currency="Rand"},
    new(){Country="Dominican Republic", Language="Spanish", LanguageCode="es-DO", CountryCode="DO", NumCode="1", Currency="Peso"},
    new(){Country="Bosnia & Herzegovina", Language="Serbian (Cyrillic)", LanguageCode="sr-Cyrl-BA", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Oman", Language="Arabic", LanguageCode="ar-OM", CountryCode="OM", NumCode="968", Currency="Rial"},
    new(){Country="Jamaica", Language="English", LanguageCode="en-JM", CountryCode="JM", NumCode="1", Currency="Dollar"},
    new(){Country="Venezuela", Language="Spanish", LanguageCode="es-VE", CountryCode="VE", NumCode="58", Currency="Bolívar"},
    new(){Country="Réunion", Language="French", LanguageCode="fr-RE", CountryCode="RE", NumCode="262", Currency="Euro"},
    new(){Country="Bosnia & Herzegovina", Language="Bosnian (Cyrillic)", LanguageCode="bs-Cyrl-BA", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Yemen", Language="Arabic", LanguageCode="ar-YE", CountryCode="YE", NumCode="967", Currency="Rial"},
    new(){Country="Colombia", Language="Spanish", LanguageCode="es-CO", CountryCode="CO", NumCode="57", Currency="Peso"},
    new(){Country="Congo - Kinshasa", Language="French", LanguageCode="fr-CD", CountryCode="CD", NumCode="243", Currency="Franc"},
    new(){Country="Serbia", Language="Serbian (Latin)", LanguageCode="sr-Latn-RS", CountryCode="RS", NumCode="381", Currency="Dinar"},
    new(){Country="Finland", Language="Inari Sami", LanguageCode="smn-Fl", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="Syria", Language="Arabic", LanguageCode="ar-SY", CountryCode="SY", NumCode="963", Currency="Pound"},
    new(){Country="Belize", Language="English", LanguageCode="en-BZ", CountryCode="BZ", NumCode="501", Currency="Dollar"},
    new(){Country="Peru", Language="Spanish", LanguageCode="es-PE", CountryCode="PE", NumCode="51", Currency="Sol"},
    new(){Country="Senegal", Language="French", LanguageCode="fr-SN", CountryCode="SN", NumCode="221", Currency="Franc"},
    new(){Country="Serbia", Language="Serbian (Cyrillic)", LanguageCode="sr-Cyrl-RS", CountryCode="RS", NumCode="381", Currency="Dinar"},
    new(){Country="Jordan", Language="Arabic", LanguageCode="ar-JO", CountryCode="JO", NumCode="962", Currency="Dinar"},
    new(){Country="Trinidad & Tobago", Language="English", LanguageCode="en-TT", CountryCode="TT", NumCode="1", Currency="Dollar"},
    new(){Country="Argentina", Language="Spanish", LanguageCode="es-AR", CountryCode="AR", NumCode="54", Currency="Peso"},
    new(){Country="Cameroon", Language="French", LanguageCode="fr-CM", CountryCode="CM", NumCode="237", Currency="Franc"},
    new(){Country="Montenegro", Language="Serbian (Latin)", LanguageCode="sr-Latn-ME", CountryCode="ME", NumCode="382", Currency="Euro"},
    new(){Country="Lebanon", Language="Arabic", LanguageCode="ar-LB", CountryCode="LB", NumCode="961", Currency="Pound"},
    new(){Country="Zimbabwe", Language="English", LanguageCode="en-ZW", CountryCode="ZW", NumCode="263", Currency="Dollar"},
    new(){Country="Ecuador", Language="Spanish", LanguageCode="es-EC", CountryCode="EC", NumCode="593", Currency="Dollar"},
    new(){Country="Côte d'Ivoire", Language="French", LanguageCode="fr-CI", CountryCode="CI", NumCode="225", Currency="Franc"},
    new(){Country="Montenegro", Language="Serbian (Cyrillic)", LanguageCode="sr-Cyrl-ME", CountryCode="ME", NumCode="382", Currency="Euro"},
    new(){Country="Kuwait", Language="Arabic", LanguageCode="ar-KW", CountryCode="KW", NumCode="965", Currency="Dinar"},
    new(){Country="Philippines", Language="English", LanguageCode="en-PH", CountryCode="PH", NumCode="63", Currency="Peso"},
    new(){Country="Chile", Language="Spanish", LanguageCode="es-CL", CountryCode="CL", NumCode="56", Currency="Peso"},
    new(){Country="Mali", Language="French", LanguageCode="fr-ML", CountryCode="ML", NumCode="223", Currency="Franc"},
    new(){Country="United Arab Emirates", Language="Arabic", LanguageCode="ar-AE", CountryCode="AE", NumCode="971", Currency="Dirham"},
    new(){Country="Uruguay", Language="Spanish", LanguageCode="es-UY", CountryCode="UY", NumCode="598", Currency="Peso"},
    new(){Country="Morocco", Language="French", LanguageCode="fr-MA", CountryCode="MA", NumCode="212", Currency="Dirham"},
    new(){Country="Bahrain", Language="Arabic", LanguageCode="ar-BH", CountryCode="BH", NumCode="973", Currency="Dinar"},
    new(){Country="Hong Kong SAR China", Language="English", LanguageCode="en-HK", CountryCode="HK", NumCode="852", Currency="Dollar"},
    new(){Country="Paraguay", Language="Spanish", LanguageCode="es-PY", CountryCode="PY", NumCode="595", Currency="Guarani"},
    new(){Country="Haiti", Language="French", LanguageCode="fr-HT", CountryCode="HT", NumCode="509", Currency="Gourde"},
    new(){Country="Qatar", Language="Arabic", LanguageCode="ar-QA", CountryCode="QA", NumCode="974", Currency="Riyal"},
    new(){Country="India", Language="English", LanguageCode="en-IN", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Bolivia", Language="Spanish", LanguageCode="es-BO", CountryCode="BO", NumCode="591", Currency="Boliviano"},
    new(){Country="Malaysia", Language="English", LanguageCode="en-MY", CountryCode="MY", NumCode="60", Currency="Ringgit"},
    new(){Country="El Salvador", Language="Spanish", LanguageCode="es-SV", CountryCode="SV", NumCode="503", Currency="Dollar"},
    new(){Country="Singapore", Language="English", LanguageCode="en-SG", CountryCode="SG", NumCode="65", Currency="Dollar"},
    new(){Country="Honduras", Language="Spanish", LanguageCode="es-HN", CountryCode="HN", NumCode="504", Currency="Lempira"},
    new(){Country="Nicaragua", Language="Spanish", LanguageCode="es-NI", CountryCode="NI", NumCode="505", Currency="Córdoba"},
    new(){Country="Puerto Rico", Language="Spanish", LanguageCode="es-PR", CountryCode="PR", NumCode="1", Currency="Dollar"},
    new(){Country="United States", Language="Spanish", LanguageCode="es-US", CountryCode="US", NumCode="1", Currency="Dollar"},
    new(){Country="Cuba", Language="Spanish", LanguageCode="es-CU", CountryCode="CU", NumCode="53", Currency="Peso"},
    new(){Country="Bosnia & Herzegovina", Language="Bosnian (Cyrillic)", LanguageCode="bs-Cyrl", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Bosnia & Herzegovina", Language="Bosnian (Latin)", LanguageCode="bs-Latn", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Serbia", Language="Serbian (Cyrillic)", LanguageCode="sr-Cyrl", CountryCode="RS", NumCode="381", Currency="Dinar"},
    new(){Country="Serbia", Language="Serbian (Latin)", LanguageCode="sr-Latn", CountryCode="RS", NumCode="381", Currency="Dinar"},
    new(){Country="Finland", Language="Inari Sami", LanguageCode="smn", CountryCode="FI", NumCode="358", Currency="Euro"},
    new(){Country="Azerbaijan", Language="Azerbaijani (Cyrillic)", LanguageCode="az-Cyrl", CountryCode="AZ", NumCode="994", Currency="Manat"},
    new(){Country="China", Language="Chinese (Simplified)", LanguageCode="zh", CountryCode="CN", NumCode="86", Currency="Yuan"},
    new(){Country="Norway", Language="Norwegian Nynorsk", LanguageCode="nn", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Bosnia & Herzegovina", Language="Bosnian", LanguageCode="bs", CountryCode="BA", NumCode="387", Currency="Convertible Mark"},
    new(){Country="Azerbaijan", Language="Azerbaijani (Latin)", LanguageCode="az-Latn", CountryCode="AZ", NumCode="994", Currency="Manat"},
    new(){Country="Uzbekistan", Language="Uzbek (Cyrillic)", LanguageCode="uz-Cyrl", CountryCode="UZ", NumCode="998", Currency="Som"},
    new(){Country="Mongolia", Language="Mongolian (Cyrillic)", LanguageCode="mn-Cyrl", CountryCode="MN", NumCode="976", Currency="Tugrik"},
    new(){Country="China", Language="Chinese (Traditional)", LanguageCode="zh-Hant", CountryCode="TW", NumCode="886", Currency="Dollar"},
    new(){Country="Norway", Language="Norwegian Bokmal", LanguageCode="nb", CountryCode="NO", NumCode="47", Currency="Krone"},
    new(){Country="Serbia", Language="Serbian", LanguageCode="sr", CountryCode="RS", NumCode="381", Currency="Dinar"},
    new(){Country="Tajikistan", Language="Tajik (Cyrillic)", LanguageCode="tg-Cyrl", CountryCode="TJ", NumCode="992", Currency="Somoni"},
    new(){Country="Germany", Language="Lower Sorbian", LanguageCode="dsb", CountryCode="DE", NumCode="49", Currency="Euro"},
    new(){Country="Uzbekistan", Language="Uzbek (Latin)", LanguageCode="uz-Latn", CountryCode="UZ", NumCode="998", Currency="Som"},
    new(){Country="India", Language="Punjabi (Arabic)", LanguageCode="pa-Arab", CountryCode="IN", NumCode="91", Currency="Rupee"},
    new(){Country="Morocco", Language="Central Atlas Tamazight (Latin)", LanguageCode="tzm-Latn", CountryCode="MA", NumCode="212", Currency="Dirham"},
    new(){Country="Nigeria", Language="Hausa (Latin)", LanguageCode="ha-Latn", CountryCode="NG", NumCode="234", Currency="Naira"},

};

    public static List<string> Countries = new List<string>() {
        "Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua & Deps",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bhutan",
"Bolivia",
"Bosnia Herzegovina",
"Botswana",
"Brazil",
"Brunei",
"Bulgaria",
"Burkina",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Central African Rep",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo",
"Congo {Democratic Rep}",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"East Timor",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Fiji",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland {Republic}",
"Israel",
"Italy",
"Ivory Coast",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea North",
"Korea South",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Mauritania",
"Mauritius",
"Mexico",
"Micronesia",
"Moldova",
"Monaco",
"Mongolia",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar, {Burma}",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russian Federation",
"Rwanda",
"St Kitts & Nevis",
"St Lucia",
"Saint Vincent & the Grenadines",
"Samoa",
"San Marino",
"Sao Tome & Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Sudan",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Togo",
"Tonga",
"Trinidad & Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Vatican City",
"Venezuela",
"Vietnam",
"Yemen",
"Zambia",
"Zimbabwe",
        };


     public static List<string> Language = new List<string>() 
     { 
        // Alhpabatically//
       "Hindi", 
       "English",
       "Tamil",
    };
}